# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --self-contained -c Release -r win-x64 -o out
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r FotoSync.zip out/FotoSync.exe out/appsettings.json
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: FotoSync.zip
        # A file, directory or wildcard pattern that describes what to upload
        path: FotoSync.zip
        # The desired behavior if no files are found using the provided path.
  
              
